config/routes.rb
Rails.application.routes.draw do

  devise_for :webusers, controllers: {
        sessions: 'webusers/sessions',
        registraions: 'webusers/registrations'
      }
  devise_scope :webuser do
    get '/webusers/login', to: 'webusers/sessions#new', as: 'login'
    get '/webusers/signup', to: 'webusers/registrations#new', as: 'signup'
  end

  namespace :admin do
    resources :categories
    resources :recipes

  end
  # mount Fae below your admin namespec
  mount Fae::Engine => '/admin'

  root :to => 'pages#home'

  get '/recipes', to: "recipes#index", as: 'recipes_index'
  get '/recipes/:slug', to: "recipes#detail", as: 'recipes_detail'


  get '/site-map', to: "about#index", as: 'about_index'


end

app/models/recipe.rb
class Recipe < ApplicationRecord
  include Fae::BaseModelConcern

  belongs_to :webuser
  belongs_to :category

  validates :title, :category, :webuser, :description, :ingredients, :instructions, presence: true

  def fae_display_field
    title
  end

end

app/controllers/admin/recipes_controller.rb
module Admin
  class RecipesController < Fae::BaseController

  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @available_years = Recipe.all
  end

  def detail
    @item = Recipe.find_by_slug(params[:slug])
    return show_404 if @item.blank?

  end

  def filter
    # render '_table', layout: false
  end

end

app/helpers/recipe_helper.rb
module RecipeHelper


end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/admin/recipes/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  header.content-header.js-content-header
    == render 'fae/shared/form_header', header: @klass_name
  == render 'fae/shared/errors'

  main.content
    = fae_input f, :title, input_class: 'slugger'
    = fae_input f, :slug
    = fae_input f, :people_it_feeds, helper_text: 'Range or Number of People Recipe Feeds'
    = fae_input f, :description, markdown: true
    = fae_input f, :ingredients, markdown: true
    = fae_input f, :instructions, markdown: true

    = fae_association f, :webuser, collection: Webuser.all
    = fae_association f, :category

app/views/admin/recipes/edit.html.slim
== render 'form'

app/views/admin/recipes/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Title
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_recipe_path(item)
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/recipes/new.html.slim
== render 'form'