config/routes.rb
Rails.application.routes.draw do

  devise_for :webusers, controllers: {
        sessions: 'webusers/sessions',
        registraions: 'webusers/registrations'
      }
  devise_scope :webuser do
    get '/webusers/login', to: 'webusers/sessions#new', as: 'login'
    get '/webusers/signup', to: 'webusers/registrations#new', as: 'signup'
  end

  namespace :admin do
    resources :categories
    resources :recipes

  end
  # mount Fae below your admin namespec
  mount Fae::Engine => '/admin'

  root :to => 'pages#home'

  get '/recipes', to: "recipes#index", as: 'recipes_index'
  get '/recipes/:slug', to: "recipes#detail", as: 'recipes_detail'


  get '/site-map', to: "about#index", as: 'about_index'


end

app/models/recipe.rb
class Recipe < ApplicationRecord
  include Fae::BaseModelConcern

  belongs_to :webuser
  belongs_to :category

  validates :title, :category, :webuser, :description, :ingredients, :instructions, presence: true

  def fae_display_field
    title
  end

end

app/controllers/admin/recipes_controller.rb
module Admin
  class RecipesController < Fae::BaseController

  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @available_years = Recipe.all
  end

  def detail
    @item = Recipe.find_by_slug(params[:slug])
    return show_404 if @item.blank?

  end

  def filter
    # render '_table', layout: false
  end

end

app/helpers/recipe_helper.rb
module RecipeHelper


end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_recipes.html.slim
- recipe ||= nil

- if recipe.present?
  .col-sm-3.single-recipe-card id="#{recipes_detail_path(recipe.slug)}"
    .card
      .card-block
        h4.recipe-text
          = truncate(recipe.title, :length => 60)
        .recipe-content
          .posted-by
            | Posted by #{recipe.webuser.name}
          h3= recipe.title
          h4= recipe.category.title
          p= recipe.description
          = link_to "I'm interested", recipes_detail_path(recipe.slug), class: 'interested'

app/views/recipes/detail.html.slim
#single-recipe-content.container
  .row
    .col-sm-6.col-sm-offset-3
      .posted-by
        | Posted by #{@item.webuser.name}
      h3= @item.title
      p= @item.category.title
      = markdown(@item.description)
      = markdown(@item.ingredients)
      = markdown(@item.instructions)