config/routes.rb
Rails.application.routes.draw do

  devise_for :webusers, controllers: {
        sessions: 'webusers/sessions',
        registraions: 'webusers/registrations'
      }
  devise_scope :webuser do
    get '/webusers/login', to: 'webusers/sessions#new', as: 'login'
    get '/webusers/signup', to: 'webusers/registrations#new', as: 'signup'
  end

  namespace :admin do
    resources :categories
    resources :recipes

  end
  # mount Fae below your admin namespec
  mount Fae::Engine => '/admin'

  root :to => 'pages#home'

  get '/recipes', to: "recipes#index", as: 'recipes_index'
  get '/recipes/:slug', to: "recipes#detail", as: 'recipes_detail'


  get '/site-map', to: "about#index", as: 'about_index'


end

app/helpers/navigation_helper.rb
module NavigationHelper

  def collapsible_links_partial_path
    if webuser_signed_in?
      'layouts/navigation/collapsible_elements/signed_in_links'
    else
      'layouts/navigation/collapsible_elements/non_signed_in_links'
    end
  end

  def body_class
    class_array = [controller_name, action_name]

    if @body_class.present?
      @body_class
    elsif @body_class_piece.present?
      class_array.push(@body_class_pieces).join(' ')
    else
      class_array.join(' ')
    end
  end

end

app/views/layouts/navigation/collapsible_elements/_non_signed_in_links.html.slim
li= link_to 'Login', login_path
li= link_to 'Signup', signup_path

app/views/layouts/navigation/collapsible_elements/_signed_in_links.html.slim
li.dropdown.pc-menu
  a#user-settings.dropdown-toggle data-toggle="dropdown" href="#"
    span#user-name= current_webuser.name
    span.caret
  ul.dropdown-menu role="menu"
    li= link_to 'Edit Profile', edit_webuser_registration_path
    li= link_to 'Log out', destroy_webuser_session_path, method: :delete
li.mobile-menu
  = link_to 'Edit Profile', edit_webuser_registration_path
li.mobile-menu
  = link_to 'Log out', destroy_webuser_session_path, method: :delete