config/routes.rb
Rails.application.routes.draw do

  devise_for :webusers, controllers: {
        sessions: 'webusers/sessions',
        registraions: 'webusers/registrations'
      }
  devise_scope :webuser do
    get '/webusers/login', to: 'webusers/sessions#new', as: 'login'
    get '/webusers/signup', to: 'webusers/registrations#new', as: 'signup'
  end

  namespace :admin do
    resources :categories
    resources :recipes

  end
  # mount Fae below your admin namespec
  mount Fae::Engine => '/admin'

  root :to => 'pages#home'

  get '/recipes', to: "recipes#index", as: 'recipes_index'
  get '/recipes/:slug', to: "recipes#detail", as: 'recipes_detail'


  get '/site-map', to: "about#index", as: 'about_index'


end

app/models/category.rb
class Category < ApplicationRecord
  include Fae::BaseModelConcern

  has_many :recipes

  validates :title, presence: true

  def fae_display_field
    title
  end

  def for_fae_index
    order(:name)
  end

end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < Fae::BaseController

  end
end

app/views/admin/categories/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  header.content-header.js-content-header
    == render 'fae/shared/form_header', header: @klass_name
  == render 'fae/shared/errors'

  main.content
    = fae_input f, :title, input_class: 'slugger'
    = fae_input f, :slug
    = fae_input f, :description

app/views/admin/categories/edit.html.slim
== render 'form'

app/views/admin/categories/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Title
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_category_path(item)
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/categories/new.html.slim
== render 'form'